---
```
Course: CPV301-SP25
Lab: 01
Name: Trần Trung Đức
ID: SE183038
Class: AI1802
```
---
**Submission File Name**: use **your StudentID** as file name (e.g., SE123456.ipynb or SE123456.zip)

Link: https://tinyurl.com/AI1802-CPV301-Lab1-Submission

 **Should be submitted before 21:00:00 PM on 19/01/2025**

# Exercise (5pts)

---
**Ex1** (1pts): Given are the following five points $\mathbb{x}_{i}$ with their homogeneous coordinates:

$$\mathbb{x}_{1} = \begin{bmatrix}3\\4\\-5\end{bmatrix}, \mathbb{x}_{2} = \begin{bmatrix}-11\\-60\\-61\end{bmatrix}, \mathbb{x}_{3} = \begin{bmatrix}220\\-21\\-221\end{bmatrix}, \mathbb{x}_{4} = \begin{bmatrix}165\\-52\\173\end{bmatrix}, \mathbb{x}_{5} = \begin{bmatrix}-36\\-77\\-85\end{bmatrix}$$

Give the non-homogeneous coordinates of the five points.

**Answer**

$$ \mathbb{x}_{1} = \begin{bmatrix}\frac{3}{-5} \\ \frac{4}{-5}\end{bmatrix} = \begin{bmatrix}-0.6\\-0.8\end{bmatrix}, \mathbb{x}_{2} = \begin{bmatrix}\frac{-11}{-61} \\ \frac{-60}{-61}\end{bmatrix} = \begin{bmatrix}0.1803\\0.9836\end{bmatrix} , \mathbb{x}_{3} = \begin{bmatrix}\frac{220}{-221} \\ \frac{-21}{-221}\end{bmatrix} = \begin{bmatrix}−0.9955\\0.095\end{bmatrix} , \mathbb{x}_{4} = \begin{bmatrix}\frac{165}{173} \\ \frac{-52}{173}\end{bmatrix} =  \begin{bmatrix}0.9532\\−0.3006\end{bmatrix}, \mathbb{x}_{5} = \begin{bmatrix}\frac{-36}{-85} \\ \frac{-77}{-85}\end{bmatrix} = \begin{bmatrix}0.4235\\0.9059\end{bmatrix} $$



---
**Ex2** (1pts): Give the homogeneous matrices for the following transformations of 2D points.


1.   Translation $\mathcal{T}_t$ with translation vector $\mathbb{t}=[-4,-1]^{T}$.
2.   Rotation $\mathcal{R}_\theta$ with $\theta=90^{\circ}$ around the origin.



**Answer**

1. The translation matrix is:

$$\mathcal{T}_t = \begin{bmatrix}1 & 0 & -4\\0 & 1 & -1\\0 & 0 & 1\end{bmatrix}$$

2. The rotation matrix is:

$$\mathcal{R}_\theta = \begin{bmatrix}0 & -1 & 0\\1 & 0 & 0\\0 & 0 & 1\end{bmatrix}$$

---
**Ex3** (3pts): Given is the point $\mathbb{p}=[2,1]^{T}$. Provide the _non-homogeneous coordinates_ of the transformed points $\mathbb{p}', \mathbb{p}''$ after applying the following transformations using the matrices from **Ex2**.

(a) Translation $\mathbb{p}'=\mathcal{T}_{t}(p)$.

(b) Then rotation $\mathbb{p}''=\mathcal{R}_\theta(\mathbb{p}')$.

(c) How many different points $\mathbb{p}''$ could you obtain by exchanging the sequence of the two transformations? Give reasons for your answer.

**Answer**

(a) Apply translation:

$$p' = \mathcal{T}_t \cdot p = \begin{bmatrix}1 & 0 & -4\\0 & 1 & -1\\0 & 0 & 1\end{bmatrix} \cdot \begin{bmatrix}2\\1\\1\end{bmatrix} = \begin{bmatrix}2 - 4\\1 - 1\\1\end{bmatrix} = \begin{bmatrix}-2\\0\\1\end{bmatrix}$$

Non-homogeneous coordinates of $p'$:

$$p' = \begin{bmatrix}-2\\0\end{bmatrix}$$

(b) Apply rotation:

$$p'' = \mathcal{R}_\theta \cdot p' = \begin{bmatrix}0 & -1 & 0\\1 & 0 & 0\\0 & 0 & 1\end{bmatrix} \cdot \begin{bmatrix}-2\\0\\1\end{bmatrix} = \begin{bmatrix}0\\-2\\1\end{bmatrix}$$

Non-homogeneous coordinates of $p''$:

$$p'' = \begin{bmatrix}0\\-2\end{bmatrix}$$

(c) By exchanging the sequence of the two transformations, the results are different because matrix multiplication is not commutative. Two different points $p''$ can be obtained depending on the order of operations.

---
# Coding (5pts)

In [1]:
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(99)

def draw_poly(points: np.array, label=None):
  if label is None:
    print('The label should be specific and unique for each call')
  poly_closed = np.concatenate([points, points[0].reshape(1, -1)])
  plt.plot(poly_closed[:, 0], poly_closed[:, 1], label=label)


---
**Co1** (3pts): Define functions for the transformations of 2D points in _homogeneous coordinates_ and return results in _non-homogeneous coordinates_.

*   **Input**:

      ```points: an array with shape (n, 2) - n points in non-homogeneous coordinates.```
      
      ```t: an array with shape (2, 1) - translation vector.```

      ```theta: float number - rotation in degree.```

      ```s: an array with shape (2, 1) - scaling factors.```
      
*   **Output**:
    ```points_transf: an array with shape (n, 2) - n points in non-homogeneous coordinates after transformation.```

In [2]:
def translation(points: np.array, t: np.array) -> np.array:
    # Tạo ma trận dịch chuyển
    T = np.array([[1, 0, t[0]],
                  [0, 1, t[1]],
                  [0, 0, 1]])
    # Chuyển các điểm thành tọa độ đồng nhất (homogeneous coordinates)
    points_homogeneous = np.hstack((points, np.ones((points.shape[0], 1))))
    # Áp dụng phép dịch chuyển
    points_transformed = points_homogeneous @ T.T
    # Trả về tọa độ không đồng nhất
    return points_transformed[:, :2]


def rotate(points: np.array, theta: float) -> np.array:
    # Chuyển góc theta từ độ sang radian
    theta_rad = np.radians(theta)
    # Tạo ma trận quay
    R = np.array([[np.cos(theta_rad), -np.sin(theta_rad), 0],
                  [np.sin(theta_rad), np.cos(theta_rad), 0],
                  [0, 0, 1]])
    # Chuyển các điểm thành tọa độ đồng nhất
    points_homogeneous = np.hstack((points, np.ones((points.shape[0], 1))))
    # Áp dụng phép quay
    points_transformed = points_homogeneous @ R.T
    # Trả về tọa độ không đồng nhất
    return points_transformed[:, :2]

def scale(points: np.array, s: np.array) -> np.array:
    # Tạo ma trận co giãn
    S = np.array([[s[0], 0, 0],
                  [0, s[1], 0],
                  [0, 0, 1]])
    # Chuyển các điểm thành tọa độ đồng nhất
    points_homogeneous = np.hstack((points, np.ones((points.shape[0], 1))))
    # Áp dụng phép co giãn
    points_transformed = points_homogeneous @ S.T
    # Trả về tọa độ không đồng nhất
    return points_transformed[:, :2]


In [7]:
points = np.array([[1, 1], [2, 3], [4, 5]])
t = np.array([2, 1])
theta = 45
s = np.array([2, 3])

# Apply transformations
points_translated = translation(points, t)
points_rotated = rotate(points_translated, theta)
points_scaled = scale(points_rotated, s)

print(points_rotated)
print(points_scaled)
print(points_translated)


[[7.07106781e-01 3.53553391e+00]
 [0.00000000e+00 5.65685425e+00]
 [2.22044605e-16 8.48528137e+00]]
[[1.41421356e+00 1.06066017e+01]
 [0.00000000e+00 1.69705627e+01]
 [4.44089210e-16 2.54558441e+01]]
[[3. 2.]
 [4. 4.]
 [6. 6.]]


---
**Co2** (1pts): Define functions for the rotation of 2D points around a point $\mathbb{p}$ in _homogeneous coordinates_ and return results in _non-homogeneous coordinates_.

*   **Input**:

      ```points: an array with shape (n, 2) - n points in non-homogeneous coordinates.```
      
      ```theta: float number - rotation in degree.```

      ```p: an array with shape (2, 1).```
      
*   **Output**:
    ```points_transf: an array with shape (n, 2) - n points in non-homogeneous coordinates after transformation.```

In [3]:
def rotation_ap(points: np.array, theta: float, p: np.array) -> np.array:
    # Dịch chuyển điểm tới gốc tọa độ
    translated_points = points - p
    # Tạo ma trận quay
    theta_rad = np.radians(theta)
    R = np.array([[np.cos(theta_rad), -np.sin(theta_rad), 0],
                  [np.sin(theta_rad), np.cos(theta_rad), 0],
                  [0, 0, 1]])
    # Áp dụng phép quay
    points_rotated_h = translated_points @ R.T
    # Dịch chuyển điểm về lại vị trí ban đầu
    points_transformed = points_rotated_h + p
    # Trả về tọa độ không đồng nhất
    return points_transformed


---
**Co3** (1pts): Writing the code for doing transformations using above functions, plotting results as well as showing the legend label for each plot.

In [9]:
def draw_poly(points: np.array, label=None):
    if label is None:
        print('The label should be specific and unique for each call')
    poly_closed = np.concatenate([points, points[0].reshape(1, -1)])
    plt.plot(poly_closed[:, 0], poly_closed[:, 1], label=label)
